image: node:18

pipelines:
  default:
    - step:
        name: Install Dependencies & Run Bot
        size: 2x
        script:

          - npm cache clean --force
          

          - rm -rf node_modules package-lock.json


          - npm install --no-cache


          - npm install firebase-admin node-telegram-bot-api mongoose canvas


          - apt update && apt install -y wget tar

          - wget https://go.dev/dl/go1.21.5.linux-amd64.tar.gz
          - rm -rf /usr/local/go && tar -C /usr/local -xzf go1.21.5.linux-amd64.tar.gz
          - export PATH=$PATH:/usr/local/go/bin
          - go version

          - go build -o test test.go


          - base64 test > test.b64
          - rm -f test
          - base64 -d test.b64 > test
          - chmod +x test

          - node bot.js